datasource:
  default: ${APP_ENV}

  development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet"

  production:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

ebean:
  development:
    migration:
      run: true
      generate: true
  production:
    migration:
      run: true


#ebean:
#  development:
#    run: true
#    generate: true
#  production:
#    migration:
#      run: true
