datasource:
  default: ${APP_ENV}

  development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet"

  production:
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
     username: ${JDBC_DATABASE_USERNAME}
     password: ${JDBC_DATABASE_PASSWORD}
     url: ${JDBC_DATABASE_URL}

#ebean:
#  development:
#    migration:
#      run: true
#  production:
#    migration:
#      run: true
ebean:
  ddl:
    run: true
    generate: true


#ebean:
#  development:
#    run: true
#    generate: true
#  production:
#    migration:
#      run: true
