datasource:
  default: ${APP_ENV}

  development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet"

  production:
    username: ${{Postgres.PGUSER}}
    password: ${{Postgres:PGPASSWORD}}
    url: jdbc:postgresql://${{Postgres.PGHOST}}:${{Postgres.PGPORT}}/${{Postgres.PGDATABASE}}

ebean:
  development:
    migration:
      run: true
      generate: true
  production:
    migration:
      run: true
#ebean:
#  development:
#    run: true
#    generate: true
#  production:
#    migration:
#      run: true
