datasource:
  default: ${APP_ENV}
  development:
    username: vitaliy25
    password: cv_ER2_r
    url: jdbc:h2:./data_base

  production:
    username: ${{Postgres:PGUSER}}
    password: ${{Postgres:PGPASSWORD}}
    url: ${{Postgres:DATABASE_URL}}

ebean:
  migration:
    run: true

#  production:
#    username: postgres
#    password: 02XUoyirr6gPRtTLn4eS
#    url: jdbc:postgresql://postgres:02XUoyirr6gPRtTLn4eS@containers-us-west-133.railway.app:6166/railway