-- apply changes
create table url_model (
  id                            integer generated by default as identity not null,
  url                           varchar(255) not null,
  responce_code                 integer not null,
  created_at                    timestamptz not null,
  updated_at                    timestamptz not null,
  constraint pk_url_model primary key (id)
);

